### ISSUE TITLE
Search with prefix

### ISSUE THREAD

**Issue by nadilas** [mosuka/blast#103]
Hi,

I was wondering if I’m doing anything wrong, but other than doing a match query I can’t seem to perform a prefix query at all. According to the bleve documentation I should be able to do that by using “prefix”: “searchterm”. However it doesn’t yield any results. Do you have an example search query for prefix?

Thanks!

**Comment by mosuka** [comment]
Hi @nadilas ,

See the following search request. You can search for documents that contain the term `search` in the `text_en` field.

```
{
  "query": {
    "query": "+text_en:search"
  },
  "size": 10,
  "from": 0,
  "fields": [
    "*"
  ],
  "sort": [
    "-_score"
  ]
}
```

**Comment by nadilas** [comment]
Hi @mosuka ,

thanks, is that a direct alternative to the http://blevesearch.com/docs/Query/#prefix ?

**Comment by mosuka** [comment]
Blast uses Bleve SearchRequest converted to JSON directly.
For more details, please see the following:
https://github.com/blevesearch/bleve/blob/75cdaca51a2ad20227868a152dfb599981b93623/search.go#L269
https://blevesearch.com/docs/Query-String-Query/

Thanks,

**Comment by nadilas** [comment]
Right, I found that. however, when I set "query" to a json instance of a PrefixQuery https://github.com/blevesearch/bleve/blob/9b6e89951d4e9207356a833a7d99577cfe249208/search/query/prefix.go
it doesn't work.

**Comment by mosuka** [comment]
Sorry, I misunderstood your question.
Please see the following JSON. You can search for documents that contain the term that has prefix `s` in the `title_en` field.

```
{
  "query": {
      "prefix": "s",
      "field": "title_en"
  },
  "size": 10,
  "from": 0,
  "fields": [
    "*"
  ],
  "sort": [
    "-_score"
  ]
}
```

**Comment by nadilas** [comment]
Okay, I'm trying to do that, but I want to search through all fields and do not restrict it to a specific one. Can "fields" accept a "*" or do I need to list all the fields where I want to search?
