### ISSUE TITLE
Multiple index

### ISSUE THREAD

**Issue by fi0** [mosuka/blast#106]
Can I run 1 indexer for multiple indexes?

**Comment by mosuka** [comment]
Hi @fi0 ,
Unfortunately, Blast does not support multiple indices. However, Bleve used by inside Blast supports pseudo multiple IndexMappings by DocumentType.
See the following Bleve documentation and the sample IndexMapping for details:
- https://blevesearch.com/docs/Index-Mapping/
- https://github.com/mosuka/blast/blob/master/example/wiki_index_mapping.json

**Comment by fi0** [comment]
thank you!
