### ISSUE TITLE
Performance test and compare performance with elasticsearch or go-geo/roit

### ISSUE THREAD

**Issue by Peipeilvcm** [mosuka/blast#111]
In some cases, performance of blast is worth being noticed.

Giving a benchmark is a good way to make users to choose this project.

**Comment by mosuka** [comment]
Hi @Peipeilvcm ,
Although it is not Blast, I published the benchmarks of Bleve (used by Blast) and other famous full-text search libraries.
Speed ​​is an important factor in selecting a full-text search library, but it is also necessary to consider whether the functional aspects such as tokenizer and filter are sufficient. However, I think it will be helpful.

https://github.com/mosuka/search-benchmark-game
https://mosuka.github.io/search-benchmark-game/
