### ISSUE TITLE
An usable web client for blast just like kibana for elasticsearch?

### ISSUE THREAD

**Issue by Peipeilvcm** [mosuka/blast#112]
For using blast easily, a web client for accessing blast seems to be a good way.

Is there an an usable web client for blast just like kibana for elasticsearch?

Or, is there an open source project to build a web client quickly for querying? 

And I have created a simple go-web for querying term and want it to support more query method like numeric range, prefix, date and so on.

May you have some suggestion? thanks.

**Comment by mosuka** [comment]
@Peipeilvcm 
Sorry for the late reply. Unfortunately, there isn't a web-based interface like a Kibana for Blast.
