### ISSUE TITLE
re-index / update an individual document

### ISSUE THREAD

**Issue by sugarme** [mosuka/blast#120]
Sorry if this had been addressed but I could not find anywhere. It is not an issue but rather a feature. Saying I have a collection of documents in MongoDB and indexed using blast. Now I update an individual document in MongoDB database, how I can reindex this document with blast?

Is there anyway that I can retrieve indexed Id of this document so that I can delete and recreate new index? Or Are there any better solution?

**Comment by mosuka** [comment]
Hi @sugarme ,
To update the index, please send the same content to Blast as the update to MongoDB.

**Comment by sugarme** [comment]
Works perfectly. Thanks.
