### ISSUE TITLE
bleve v2 and blast

### ISSUE THREAD

**Issue by gedw99** [mosuka/blast#144]
level v2 is moving forward fast and i think blast can gain from it.

bleve has changed storage formats almost as much as how often it rains, but v2 looks at this point to be more stable.

https://github.com/blevesearch/blevex/pull/50/files

**Comment by mosuka** [comment]
@gedw99 
Thank you for letting me know. I'll try it when I have time.

Thanks! :)

**Comment by joe-getcouragenow** [comment]
:) awesome !!!
