### ISSUE TITLE
Indexing content / faceted search

### ISSUE THREAD

**Issue by roscopecoltran** [mosuka/blast#2]
Hey,

Hope you are all well !

I wanted to extend the following golang project, https://github.com/hoop33/limo, using also bleve, with **blast**. Actually, I forked and updated limo in order to automatically fetch and add the repo topics in order to pre-fill limo's tags index.

But I would like to create a web-ui and create some facets to explore my starred repository.  So after a couple of searches, I found your project wrapping the bleve package.

Can you provide an example or more explanation about how to index content ?
- Content to index: https://github.com/hoop33/limo/blob/master/model/star.go
- Current indexer: https://github.com/hoop33/limo/blob/master/model/index.go

Questions:
- How to integrate blast into another go app ?
- How to configure blast for managing those facets ?
- How to auto-increment the next doc id to index automatically ? 
- Is it possible to load some white/stop/watch words to match (eg. https://github.com/porter-io/tagg-python/blob/master/tagg/default_defs.json) while indexing a new content ?

Thanks in advance.

Cheers,
Richard

**Comment by mosuka** [comment]
Hi @roscopecoltran ,

- How to integrate blast into another go app ?
    - Please use gRPC client or HTTP REST API.

- How to configure blast for managing those facets ?
    - If you mean managing index mapping, please see Bleve document.
http://blevesearch.com/docs/Index-Mapping/

- How to auto-increment the next doc id to index automatically ?
    - Unfortunately, Bleve doesn't support it.

- Is it possible to load some white/stop/watch words to match (eg. https://github.com/porter-io/tagg-python/blob/master/tagg/default_defs.json) while indexing a new content ?
    - You need to convert JSON formatted document for Blast. Please see examples.
https://github.com/mosuka/blast/tree/master/example
