### ISSUE TITLE
Failing docker containers with "No help topic for 'blastd'"

### ISSUE THREAD

**Issue by klausondrag** [mosuka/blast#23]
### summary
The docker container seems to be broken. Instead of starting up properly they fail and exit.

### steps to reproduce
```
docker pull mosuka/blast:latest
docker-compose up
```

### expected result
A cluster of blast should be running and available over the network.

### actual result
The terminal output is `No help topic for 'blastd'`for every node and the nodes are restarted. They exit with `blast_blast1_1 exited with code 3`.

**Comment by mosuka** [comment]
Hi @klausondrag, 
Sorry for the inconvenience. The master branch is under development.
Could you use v0.3.2 tag.

https://github.com/mosuka/blast/tree/v0.3.2

**Comment by klausondrag** [comment]
I see. That solved my problem, thanks!
