### ISSUE TITLE
Add federated search

### ISSUE THREAD

**Issue by mosuka** [mosuka/blast#30]

**Comment by gedw99** [comment]
YOu mean like Etcd, so that when nodes come up they can tell etcd and then all the other blast nodes are told ?

**Comment by mosuka** [comment]
Hi @gedw99,

Yes. Current Blast can replicate data, but it can not distributed search and indexing like a Solr or an Elasticsearch. To perform a distributed search and indexing across multiple Blast clusters(as index shards), It needs to manage the cluster information like a Solr's ZooKeeper or an Elasticsearch's master node.
There are several ways to do this:
- Use etcd-io/etcd or hashicorp/consul (like a Solr)
- Develop and use own management node (like an Elasticsearch)
Although the management node needs fault tolerance, the indexer implementation has already succeeded in replicating data, so use that know-how to develop Blast dedicated management node like an Elasticsearch.

**Comment by gedw99** [comment]
I was playing with federation branch yesterday.

Can't wait to try this out.
Fantastic work !!
