### ISSUE TITLE
Language contribute

### ISSUE THREAD

**Issue by mhf-ir** [mosuka/blast#6]
How can we add new language for better indexing?

**Comment by gedw99** [comment]
i think thats related to Bleve, not Blast.
Have a look in the Bleve repo...

**Comment by mosuka** [comment]
Hi @mhf-ir, 

As @gedw99 seys, Blast just uses Bleve.
If you want to contribute new language analyzer, please contact to Bleve project.

**Comment by gedw99** [comment]
these are the stemmers in x package for bleve
https://github.com/blevesearch/blevex/tree/master/lang
