### ISSUE TITLE
Management of federated cluster

### ISSUE THREAD

**Issue by gedw99** [mosuka/blast#61]
What's the suggested plan for management of the federated cluster ?

Try to be DRY and use the standard tracing, logging, metrics solutions out there in golang land.
This enables a dev to bring blast up and have the insight without learning new tools.

Am wondering if we should build a web based dashboard to provide the ability for a developer ( rather than a SRE ) to play with blast but also to have a single management pane seperate from the normal SRE stuff

**Comment by mosuka** [comment]
Hi @gedw99 ,
I'm planning to support Prometheus and Grafana to monitor Blast. Prometheus and Grafana are famous and popular system surveillance systems.
I have already implemented metrics exposition endpoint for Prometheus (`/metrics`).
Current metrics are not sufficient for system monitoring but will be expanded in the future.

**Comment by gedw99** [comment]
sounds good :)
