### ISSUE TITLE
Possible to build a Blind index using blast?

### ISSUE THREAD

**Issue by StevenACoffman** [mosuka/blast#83]
We have security requirements that require the use of encryption at rest. We would like to be able to build an index of the unencrypted plain text, and then ship the index and the encrypted data files, without leaking the plain text. Is this something that is possible with blast/bleve?

**Comment by mosuka** [comment]
Hi,
While Blast will be able to encrypt HTTP and gRPC communications using TLS, it is difficult to encrypt the index itself. I'll create an issue about using TLS.
Thanks.
